# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4d1a7202f79d0708092d8e5edea58f7d0a0b80f7bf69b5a199dbb918ee070c92ba71c00041360a61a971267e0142a1aa194297573ad1204bb01d49c08af204f

test:
  secret_key_base: 5cf64bd6685e224d2c5ebc285c617eb23aedc8c568ec9cf7d7e4e70182ebeebd5421bed08050bdca7101150cb725d26fcdd1bfc3f21777c63f30ea2f7b5e46be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
